name: T-2
favicon: null
layout_spectrum: 0.4075803104788065
typography_spectrum: 0.6347964846063405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#303b2c'
    - '#00090b'
    - '#76645b'
    - '#97867f'
  brandStrength: 0.48658400657586753
  lightness: 0.0726012100931257
  saturation: 0.8605213398113847
  rhythmicContrast: 0.1849074603524059
purpose: []
